# Generated by Django 4.0.4 on 2022-05-15 03:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('sale_type', models.CharField(choices=[('for sale', 'For Sale'), ('for rent', 'For Rent')], default='for sale', max_length=50)),
                ('home_type', models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Town House', 'Townhouse')], default='House', max_length=50)),
                ('sqft', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo_main', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_7', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_8', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_9', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_10', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_11', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_12', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_13', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_14', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_15', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_16', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_17', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_18', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_19', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo_20', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realtors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
