# Generated by Django 4.0.3 on 2022-05-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_price_alter_listing_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='open_house',
            field=models.BooleanField(default=False),
        ),
    ]
